# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  create_infrastructure:
    #   docker:
    #     - image: amazon/aws-cli
    #   steps:
    #     - checkout
    #     - run: aws cloudformation create-stack
    #         --stack-name circleci-demo-deploy
    #         --template-body file://template.yml
    #         --region=us-east-1
    # create_web_server:
    # docker:
    #   - image: python:3.7-alpine3.11
    # steps:
    #   - checkout
    #   - add_ssh_keys:
    #       fingerprints: [0e:26:07:d1:07:cb:0c:0c:9b:06:5b:e0:f8:50:c1:3d]
    #   - run:
    #       name: Install dependencies
    #       command: |
    #         apk add --update ansible
    #   - run:
    #       name: Configure server
    #       command: |
    #         ansible-playbook -i inventory.txt playbook.yml
  smoke_test_error:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: curl -s --head "https://www.kevinedm0nd.com/"
  print_test_error:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: return 1
      - run:
          name: Print Failure Alert
          command: echo "Job Failure Alert"
          when: on_fail

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - smoke_test_error
      - print_test_error
